# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.define "web" do |web|
        web.vm.network "private_network", ip: "192.168.56.42"
        config.vm.provision "ansible" do |ansible|
            ansible.inventory_path = "./inventory"
            ansible.playbook = "bootstrap.yaml"
            ansible.extra_vars = {
                ansible_ssh_user: 'vagrant',
                ansible_ssh_private_key_file: './.vagrant/machines/default/virtualbox/private_key'
            }
            ansible.limit = "192.168.56.42"
        end
    end

    config.vm.define "db" do |db|
        config.vm.network "private_network", ip: "192.168.56.43"
    end
end
